name: Compilar Linguagem Carlos

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código-fonte
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y flex bison build-essential

      - name: Gerar parser com Bison e lexer com Flex
        run: |
          bison -d parser.y
          flex lexer.l

      - name: Compilar o compilador Carlos
        run: |
          g++ lex.yy.c parser.tab.c -o carlos -lfl
